name: Run local test for ransomwatch

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '0 */2+1 * * *'

jobs:
  splash-container:
     runs-on: ubuntu-latest

     strategy:
       matrix:
         python-version: ["3.10"]

     steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{matrix.python-version}}
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install system deps
        run: |
          # playwright required deps.
          sudo apt install libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libxkbcommon0 libxdamage1 libgbm1 libpango-1.0-0 libcairo2 libatspi2.0-0 tor
          sudo apt install 
          python -m pip install --upgrade pip poetry
      - name: Install & run Ransomlook
        run: |
          echo RANSOMLOOK_HOME="'`pwd`'" > .env
          cp config/generic.json.sample config/generic.json
          cp data/posts.json.sample data/posts.json
          cp data/groups.json.sample data/groups.json
          poetry install -vvv
          poetry run playwright install
      - name: Run test
        run: |
          sudo service tor start
          poetry run scrape
          poetry run parse
          poetry run markdown
          mv data/groups.json data/groups.json.sample
          mv posts/groups.json data/posts.json.sample
      - name: save changes
        run: |  
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git commit --all --message "ğšŒğš›ğš˜ğš—ğš‹ğš˜ğš" || echo "no changes to commit"
          git push
